[workspace]
members = ["dashtool", "dashtool-common", "argo-workflow"]

resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[patch.crates-io]
object_store = { version = "0.11.1", git = "https://github.com/apache/arrow-rs", rev = "c60ce14" }

